/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ABreadcrumb: typeof import('ant-design-vue/es')['Breadcrumb']
    ABreadcrumbItem: typeof import('ant-design-vue/es')['BreadcrumbItem']
    AButton: typeof import('ant-design-vue/es')['Button']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    ATreeSelect: typeof import('ant-design-vue/es')['TreeSelect']
    ContentRouterPage: typeof import('./src/components/contentRouterPage.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterPage: typeof import('./src/components/RouterPage.vue')['default']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
