export const Study:any = [
    {
        name:'CSS艺术之美',
        children:[
            {
                name:'基础篇',
                children:[
                    {
                        name:'剧中'
                    },
                    {
                        name:'单位'
                    },
                    {
                        name:'颜色'
                    },
                    {
                        name:'变量'
                    },
                    {
                        name:'选择器'
                    },
                    {
                        name:'Sass'
                    },
                    {
                        name:'Flex布局'
                    },
                    {
                        name:'Grid布局'
                    },
                    {
                        name:'数学函数'
                    },
                    {
                        name:'Flex vs Grid'
                    }
                ]
            },
            {
                name:'进阶篇',
                children:[
                    {name:'框架'},
                    {name:'技巧'},
                    {name:'优化'},
                    {name:'方法论'},
                    {name:'容器查询'},
                    {name:'网页置灰'},
                    {name:'样式重置'},
                    {name:'文本换行'},
                    {name:'隐藏元素'},
                    {name:'溢出问题'},
                    {name:'父选择器'},
                    {name:'高级选择器'},
                    {name:'选择器性能'},
                    {name:'背景图vs<img>'},
                    {name:'Tailwind css'},
                ]
            },
            {
                name:'效果篇',
                children:[
                    {name:'实现三角形'},
                    {name:'实现九宫格'},
                    {name:'实现3D骰子'},
                ]
            },
            {
                name:'最新动态',
                children:[
                    {name:'可扩展Css的演变'},
                    {name:'新特性'},
                ]
            }
        ]
    },
    {
        name:'JavaScript',
        children:[
            {name:'现代深拷贝'},
            {
                name:'基础篇',
                children:[
                    {name:'数组'},
                    {name:'JSON'},
                    {name:'字符串'},
                    {name:'操作符'},
                    {name:'Infinity'},
                    {name:'数据类型'},
                    {name:'类型转换'},
                    {name:'循环遍历'},
                    {name:'引号区别'},
                    {name:'错误类型'},
                    {name:'深浅拷贝'},
                    {name:'结构赋值'},
                    {name:'变量提升'},
                    {name:'对象不变性'},
                    {name:'正则表达式'},
                    {name:'ES6-ES13'},
                ]
            },
            {
                name:'进阶篇',
                children:[
                    {name:'this'},
                    {name:'闭包'},
                    {name:'reduce'},
                    {name:'二进制'},
                    {name:'时间日期'},
                    {name:'字符编码'},
                    {name:'错误处理'},
                    {name:'内存泄漏'},
                    {name:'异步编程'},
                    {name:'事件循环'},
                    {name:'竞态条件'},
                    {name:'web api'},
                    {name:'前端模块化'},
                    {name:'V8执行原理'},
                    {name:'虚拟键盘Api'},
                    {name:'迭代器&生成器'},
                ]
            },
            {
                name:'技巧篇',
                children:[
                    {name:'对象处理'},
                    {name:'条件语句'},
                    {name:'调试技巧'},
                    {name:'命名约定'},
                    {name:'开发技巧'},
                    {name:'单行代码'},
                    {name:'工具函数'},
                    {name:'Eslint异步'},
                ]
            },
            {
                name:'最新动态',
                children:[
                    {name:'ECMAScript 2022'},
                ]
            }
        ]
    }
]